### ISSUE TITLE
bug in crack_atof()

### ISSUE THREAD

**Issue by TianBo-Timothy** [shaovoon/floatbench#1]
When parsing "-1.23456789012", the function crack_atof() returns `-20.2941`, which is incorrect.

The problem is that `divisorForFraction` is an integer. When the fraction part is very long, the integer will overflow.

The easiest fix could be to change it to double.

**Comment by TianBo-Timothy** [comment]
I made a fixed version which can be found at http://coliru.stacked-crooked.com/a/2e28f0d71f47ca5e

In this version, I also added exponent support and slightly further improved performance by around 10%.

**Comment by shaovoon** [comment]
Thanks for the fix, I have add your crack_atof to the benchmark.

**Comment by TianBo-Timothy** [comment]
Can you please update the README to remove the comment on crack_atof() "Cannot convert float string in scientific notation." as it now handles scientific notation as well?
